[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# Auto-updated by: bun run scripts/init-wallets.ts
[programs.devnet]
mirage_bridge = "4taEm2D4skz4sPCMJEnLhF9XSDoULtgnn85M1bxbWA2c"

[programs.localnet]
mirage_bridge = "4taEm2D4skz4sPCMJEnLhF9XSDoULtgnn85M1bxbWA2c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/mirage-bridge-authority.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
